name: dump pr context

on:
  pull_request:
    types: [auto_merge_enabled]

jobs:
  dump-pr-context:

    runs-on: ubuntu-latest

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1