name: set version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      retries:
        type: number
        required: true
        default: 3

permissions:
  contents: write

jobs:
  set-version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set-version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email ''
          echo "${{ inputs.version }}" > VERSION
          git add VERSION
          git commit --allow-empty -m "set version ${{ inputs.version }}"
          git tag ${{ inputs.version }} -m "version ${{ inputs.version }}"
          retries=${{ inputs.retries }}

            git fetch
            git rebase origin/${git branch --show-current}

          until git push --follow-tags; do
            retries=$((retries-1))
            if (( $retries < 1 )); then
              echo failed to push
              exit 1
            fi
            git fetch
            git rebase origin/${git branch --show-current}
          }
          done
