name: set version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  bump-version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set-version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email ''
          echo "${{ inputs.version }}" > VERSION
          git add VERSION
          git commit --amend --no-edit
          git tag ${{ inputs.version }} -m "version ${{ inputs.version }}"
          git push --force-with-lease --follow-tags
