name: version

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [set version]
    types: [completed]

jobs:
  version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git describe
        run: git describe --tags
